# Generated by Django 5.2.7 on 2026-01-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_rut',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='comuna',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='plazo_entrega',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
