# Generated by Django 5.2.7 on 2025-11-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='usa_contrasena_temporal',
            field=models.BooleanField(default=True),
        ),
    ]
