# Generated by Django 5.2.7 on 2025-11-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ultima_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ultima_sesion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
