# Generated by Django 5.2.7 on 2025-11-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfilusuario_ultima_modificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
