# Generated by Django 5.2.7 on 2025-10-14 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_atributo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('fecha', 'Fecha'), ('booleano', 'Booleano')], max_length=10)),
                ('categorias', models.ManyToManyField(blank=True, to='productos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.categoria')),
                ('marcas', models.ManyToManyField(blank=True, to='productos.marca')),
            ],
        ),
        migrations.CreateModel(
            name='ValorAtributoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_numero', models.FloatField(blank=True, null=True)),
                ('valor_fecha', models.DateField(blank=True, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.atributo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='productos.producto')),
            ],
        ),
    ]
