# Generated by Django 5.2.7 on 2025-10-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_fabricante_modelofabricante_productocompatibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('operación', models.CharField(max_length=10)),
                ('productos', models.IntegerField()),
            ],
        ),
    ]
