# Generated by Django 5.2.7 on 2025-10-20 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='log',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='log',
            name='operación',
        ),
        migrations.RemoveField(
            model_name='log',
            name='productos',
        ),
        migrations.AddField(
            model_name='log',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='modelo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='operacion',
            field=models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('CONSULTAR', 'Consultar')], max_length=15, null=True),
        ),
    ]
