# Generated by Django 5.2.7 on 2025-10-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_log_fecha_remove_log_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='descripcion',
            new_name='detalle',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='modelo',
            new_name='entidad',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='fecha_hora',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='log',
            name='operacion',
        ),
        migrations.AddField(
            model_name='log',
            name='accion',
            field=models.CharField(choices=[('AGREGAR', 'Agregar'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('CONSULTAR', 'Consultar')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
