# Generated by Django 5.2.7 on 2025-10-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_rename_descripcion_log_detalle_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marca',
            new_name='Proveedor',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='marca',
            new_name='proveedor',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='marcas',
            new_name='proveedores',
        ),
    ]
