# Generated by Django 5.2.7 on 2025-10-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_rename_marca_proveedor_rename_marca_modelo_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricante',
            options={'verbose_name': 'Fabricante', 'verbose_name_plural': 'Fabricantes'},
        ),
        migrations.AlterModelTable(
            name='fabricante',
            table='productos_fabricante',
        ),
    ]
