# Generated by Django 5.2.7 on 2025-10-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_fabricante_options_alter_fabricante_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricante',
            options={},
        ),
        migrations.AlterModelTable(
            name='fabricante',
            table=None,
        ),
    ]
