# Generated by Django 5.2.7 on 2025-10-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='modelos_compatibles',
            field=models.ManyToManyField(related_name='productos_compatibles', through='productos.ProductoCompatibilidad', to='productos.modelofabricante'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(blank=True, related_name='productos', to='productos.proveedor'),
        ),
    ]
