# Generated by Django 5.2.7 on 2025-11-03 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_fix_atributo_categorias'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imagenproducto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='modelos_compatibles',
        ),
        migrations.RemoveField(
            model_name='productocompatibilidad',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='productocompatibilidad',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='valoratributoproducto',
            name='atributo',
        ),
        migrations.RemoveField(
            model_name='valoratributoproducto',
            name='valor_booleano',
        ),
        migrations.RemoveField(
            model_name='valoratributoproducto',
            name='valor_fecha',
        ),
        migrations.RemoveField(
            model_name='valoratributoproducto',
            name='valor_numero',
        ),
        migrations.RemoveField(
            model_name='valoratributoproducto',
            name='valor_texto',
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_atributo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo_fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.modelofabricante'),
        ),
        migrations.AddField(
            model_name='productocompatibilidad',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productocompatibilidad',
            name='key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productocompatibilidad',
            name='producto_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades_principales', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='productocompatibilidad',
            name='producto_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades_relacionadas', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='valoratributoproducto',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='valoratributoproducto',
            name='key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='productos.proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='valoratributoproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valores_atributo', to='productos.producto'),
        ),
        migrations.RemoveField(
            model_name='imagenproducto',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='imagenproducto',
            name='url',
        ),
    ]
