# Generated by Django 5.2.7 on 2026-01-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_alter_imagenproducto_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoratributoproducto',
            name='atributo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='productos.atributo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valoratributoproducto',
            name='valor_booleano',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valoratributoproducto',
            name='valor_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valoratributoproducto',
            name='valor_numero',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='valoratributoproducto',
            name='valor_texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valoratributoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='productos.producto'),
        ),
        migrations.CreateModel(
            name='ArchivoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('key', models.CharField(blank=True, default='', max_length=255)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='productos.producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='valoratributoproducto',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='valoratributoproducto',
            name='key',
        ),
    ]
