# Generated by Django 5.2.7 on 2026-01-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_alter_valoratributoproducto_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoproducto',
            name='key',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='valoratributoproducto',
            unique_together={('producto', 'atributo')},
        ),
    ]
