# Generated by Django 5.2.7 on 2026-01-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_alter_archivoproducto_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributo',
            name='nombre',
            field=models.TextField(),
        ),
    ]
